# EasySocialMedia Configuration
# Customize commands and permissions here

settings:
  # Main command settings
  main-command:
    name: "esm"
    aliases: ["easysocial"]
    enabled: true
    permission: "esm.admin"

  # Social media command settings
  social-command:
    name: "social"
    aliases: ["links"]
    enabled: true
    permission: "esm.use"

  # Update checker settings
  update-checker:
    enabled: true

# Custom commands configuration
commands:
  # Example: Discord command
  discord:
    message: "&9Our Discord: https://discord.gg/example"

  # Example: YouTube command
  youtube:
    message: "&cOur YouTube: https://youtube.com/example"